CREATE CONSTRAINT person_id_unique IF NOT EXISTS FOR (n:Person) REQUIRE n.person_id IS UNIQUE;
CREATE CONSTRAINT location_id_unique IF NOT EXISTS FOR (n:Location) REQUIRE n.location_id IS UNIQUE;
CREATE CONSTRAINT case_id_unique IF NOT EXISTS FOR (n:Case) REQUIRE n.case_id IS UNIQUE;
CREATE CONSTRAINT phone_id_unique IF NOT EXISTS FOR (n:Phone) REQUIRE n.phone_id IS UNIQUE;
CREATE CONSTRAINT vehicle_id_unique IF NOT EXISTS FOR (n:Vehicle) REQUIRE n.vehicle_id IS UNIQUE;
CREATE CONSTRAINT account_id_unique IF NOT EXISTS FOR (n:Account) REQUIRE n.account_id IS UNIQUE;
CREATE CONSTRAINT transaction_id_unique IF NOT EXISTS FOR (n:Transaction) REQUIRE n.transaction_id IS UNIQUE;
CREATE CONSTRAINT evidence_id_unique IF NOT EXISTS FOR (n:Evidence) REQUIRE n.evidence_id IS UNIQUE;

MERGE (p:Person {person_id:'P001'}) SET p.name='Ravi Sharma', p.age=32;
MERGE (p:Person {person_id:'P002'}) SET p.name='Suresh Rao', p.age=38;
MERGE (p:Person {person_id:'P003'}) SET p.name='Anil Verma', p.age=29;
MERGE (p:Person {person_id:'P004'}) SET p.name='Meena Kapoor', p.age=35;
MERGE (p:Person {person_id:'P005'}) SET p.name='Arjun Singh', p.age=41;
MERGE (p:Person {person_id:'P006'}) SET p.name='Kiran Reddy', p.age=34;
MERGE (p:Person {person_id:'P007'}) SET p.name='Neha Patel', p.age=28;
MERGE (p:Person {person_id:'P008'}) SET p.name='Vikram Das', p.age=40;
MERGE (p:Person {person_id:'P009'}) SET p.name='Priya Nair', p.age=31;
MERGE (p:Person {person_id:'P010'}) SET p.name='Rahul Mehta', p.age=36;
MERGE (p:Person {person_id:'P011'}) SET p.name='Sneha Rao', p.age=27;
MERGE (p:Person {person_id:'P012'}) SET p.name='Manoj Kumar', p.age=43;
MERGE (p:Person {person_id:'P013'}) SET p.name='Asha Verma', p.age=30;
MERGE (p:Person {person_id:'P014'}) SET p.name='Rohit Shah', p.age=39;
MERGE (p:Person {person_id:'P015'}) SET p.name='Divya Singh', p.age=33;

MERGE (l:Location {location_id:'L001'}) SET l.location_name='Jubilee Hills', l.city='Hyderabad';
MERGE (l:Location {location_id:'L002'}) SET l.location_name='Banjara Hills', l.city='Hyderabad';
MERGE (l:Location {location_id:'L003'}) SET l.location_name='Kukatpally', l.city='Hyderabad';
MERGE (l:Location {location_id:'L004'}) SET l.location_name='Secunderabad', l.city='Hyderabad';
MERGE (l:Location {location_id:'L005'}) SET l.location_name='Madhapur', l.city='Hyderabad';
MERGE (l:Location {location_id:'L006'}) SET l.location_name='Gachibowli', l.city='Hyderabad';
MERGE (l:Location {location_id:'L007'}) SET l.location_name='Ameerpet', l.city='Hyderabad';
MERGE (l:Location {location_id:'L008'}) SET l.location_name='Begumpet', l.city='Hyderabad';

MERGE (c:Case {case_id:'C1042'}) SET c.crime_type='Robbery', c.case_date=date('2026-08-12'), c.status='Under Investigation', c.location_id='L001';
MERGE (c:Case {case_id:'C0817'}) SET c.crime_type='Robbery', c.case_date=date('2025-11-18'), c.status='Closed', c.location_id='L002';
MERGE (c:Case {case_id:'C0562'}) SET c.crime_type='Robbery', c.case_date=date('2025-05-03'), c.status='Closed', c.location_id='L003';
MERGE (c:Case {case_id:'C0301'}) SET c.crime_type='Theft', c.case_date=date('2024-09-21'), c.status='Closed', c.location_id='L001';
MERGE (c:Case {case_id:'C1205'}) SET c.crime_type='Robbery', c.case_date=date('2026-08-20'), c.status='Under Investigation', c.location_id='L005';
MERGE (c:Case {case_id:'C1210'}) SET c.crime_type='Theft', c.case_date=date('2026-08-22'), c.status='Under Investigation', c.location_id='L006';
MERGE (c:Case {case_id:'C1215'}) SET c.crime_type='Fraud', c.case_date=date('2026-08-25'), c.status='Under Investigation', c.location_id='L007';
MERGE (c:Case {case_id:'C1220'}) SET c.crime_type='Robbery', c.case_date=date('2026-08-28'), c.status='Under Investigation', c.location_id='L005';
MERGE (c:Case {case_id:'C1225'}) SET c.crime_type='Theft', c.case_date=date('2026-08-30'), c.status='Closed', c.location_id='L008';
MERGE (c:Case {case_id:'C1230'}) SET c.crime_type='Fraud', c.case_date=date('2026-09-01'), c.status='Under Investigation', c.location_id='L006';

MERGE (ph:Phone {phone_id:'PH001'}) SET ph.phone_number='9678905678';
MATCH (p:Person {person_id:'P001'}), (ph:Phone {phone_id:'PH001'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH002'}) SET ph.phone_number='8982576687';
MATCH (p:Person {person_id:'P002'}), (ph:Phone {phone_id:'PH002'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH003'}) SET ph.phone_number='7867903423';
MATCH (p:Person {person_id:'P003'}), (ph:Phone {phone_id:'PH003'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH004'}) SET ph.phone_number='8090675932';
MATCH (p:Person {person_id:'P004'}), (ph:Phone {phone_id:'PH004'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH005'}) SET ph.phone_number='9876502005';
MATCH (p:Person {person_id:'P006'}), (ph:Phone {phone_id:'PH005'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH006'}) SET ph.phone_number='8765402006';
MATCH (p:Person {person_id:'P007'}), (ph:Phone {phone_id:'PH006'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH007'}) SET ph.phone_number='7654302007';
MATCH (p:Person {person_id:'P008'}), (ph:Phone {phone_id:'PH007'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH008'}) SET ph.phone_number='9123402008';
MATCH (p:Person {person_id:'P009'}), (ph:Phone {phone_id:'PH008'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH009'}) SET ph.phone_number='9988702009';
MATCH (p:Person {person_id:'P010'}), (ph:Phone {phone_id:'PH009'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH010'}) SET ph.phone_number='8899102010';
MATCH (p:Person {person_id:'P011'}), (ph:Phone {phone_id:'PH010'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH011'}) SET ph.phone_number='7766502011';
MATCH (p:Person {person_id:'P012'}), (ph:Phone {phone_id:'PH011'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH012'}) SET ph.phone_number='9345602012';
MATCH (p:Person {person_id:'P013'}), (ph:Phone {phone_id:'PH012'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH013'}) SET ph.phone_number='9654302013';
MATCH (p:Person {person_id:'P014'}), (ph:Phone {phone_id:'PH013'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH014'}) SET ph.phone_number='8123402014';
MATCH (p:Person {person_id:'P015'}), (ph:Phone {phone_id:'PH014'}) MERGE (p)-[:USES]->(ph);
MERGE (ph:Phone {phone_id:'PH015'}) SET ph.phone_number='9234502015';
MATCH (p:Person {person_id:'P015'}), (ph:Phone {phone_id:'PH015'}) MERGE (p)-[:USES]->(ph);


MERGE (v:Vehicle {vehicle_id:'V001'}) SET v.vehicle_type='White SUV', v.registration_no='TEST-V001';
MATCH (p:Person {person_id:'P001'}), (v:Vehicle {vehicle_id:'V001'}) MERGE (p)-[:OWNS]->(v);
MERGE (v:Vehicle {vehicle_id:'V002'}) SET v.vehicle_type='Black Sedan', v.registration_no='TEST-V002';
MATCH (p:Person {person_id:'P002'}), (v:Vehicle {vehicle_id:'V002'}) MERGE (p)-[:OWNS]->(v);
MERGE (v:Vehicle {vehicle_id:'V003'}) SET v.vehicle_type='Blue Bike', v.registration_no='TEST-V003';
MATCH (p:Person {person_id:'P003'}), (v:Vehicle {vehicle_id:'V003'}) MERGE (p)-[:OWNS]->(v);
MERGE (v:Vehicle {vehicle_id:'V004'}) SET v.vehicle_type='Black SUV', v.registration_no='TEST-V004';
MATCH (p:Person {person_id:'P006'}), (v:Vehicle {vehicle_id:'V004'}) MERGE (p)-[:OWNS]->(v);
MERGE (v:Vehicle {vehicle_id:'V005'}) SET v.vehicle_type='White Sedan', v.registration_no='TEST-V005';
MATCH (p:Person {person_id:'P007'}), (v:Vehicle {vehicle_id:'V005'}) MERGE (p)-[:OWNS]->(v);
MERGE (v:Vehicle {vehicle_id:'V006'}) SET v.vehicle_type='Grey Hatchback', v.registration_no='TEST-V006';
MATCH (p:Person {person_id:'P008'}), (v:Vehicle {vehicle_id:'V006'}) MERGE (p)-[:OWNS]->(v);
MERGE (v:Vehicle {vehicle_id:'V007'}) SET v.vehicle_type='Red Bike', v.registration_no='TEST-V007';
MATCH (p:Person {person_id:'P010'}), (v:Vehicle {vehicle_id:'V007'}) MERGE (p)-[:OWNS]->(v);
MERGE (v:Vehicle {vehicle_id:'V008'}) SET v.vehicle_type='Blue Sedan', v.registration_no='TEST-V008';
MATCH (p:Person {person_id:'P012'}), (v:Vehicle {vehicle_id:'V008'}) MERGE (p)-[:OWNS]->(v);
MERGE (v:Vehicle {vehicle_id:'V009'}) SET v.vehicle_type='Silver SUV', v.registration_no='TEST-V009';
MATCH (p:Person {person_id:'P014'}), (v:Vehicle {vehicle_id:'V009'}) MERGE (p)-[:OWNS]->(v);
MERGE (v:Vehicle {vehicle_id:'V010'}) SET v.vehicle_type='Black Bike', v.registration_no='TEST-V010';
MATCH (p:Person {person_id:'P015'}), (v:Vehicle {vehicle_id:'V010'}) MERGE (p)-[:OWNS]->(v);


MERGE (a:Account {account_id:'A001'}) SET a.account_type='Savings';
MATCH (p:Person {person_id:'P001'}), (a:Account {account_id:'A001'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A002'}) SET a.account_type='Savings';
MATCH (p:Person {person_id:'P002'}), (a:Account {account_id:'A002'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A003'}) SET a.account_type='Business';
MATCH (p:Person {person_id:'P003'}), (a:Account {account_id:'A003'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A004'}) SET a.account_type='Savings';
MATCH (p:Person {person_id:'P006'}), (a:Account {account_id:'A004'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A005'}) SET a.account_type='Business';
MATCH (p:Person {person_id:'P007'}), (a:Account {account_id:'A005'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A006'}) SET a.account_type='Savings';
MATCH (p:Person {person_id:'P008'}), (a:Account {account_id:'A006'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A007'}) SET a.account_type='Savings';
MATCH (p:Person {person_id:'P009'}), (a:Account {account_id:'A007'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A008'}) SET a.account_type='Business';
MATCH (p:Person {person_id:'P010'}), (a:Account {account_id:'A008'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A009'}) SET a.account_type='Savings';
MATCH (p:Person {person_id:'P011'}), (a:Account {account_id:'A009'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A010'}) SET a.account_type='Savings';
MATCH (p:Person {person_id:'P012'}), (a:Account {account_id:'A010'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A011'}) SET a.account_type='Business';
MATCH (p:Person {person_id:'P013'}), (a:Account {account_id:'A011'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A012'}) SET a.account_type='Savings';
MATCH (p:Person {person_id:'P014'}), (a:Account {account_id:'A012'}) MERGE (p)-[:OWNS]->(a);
MERGE (a:Account {account_id:'A013'}) SET a.account_type='Savings';
MATCH (p:Person {person_id:'P015'}), (a:Account {account_id:'A013'}) MERGE (p)-[:OWNS]->(a);

MERGE (t:Transaction {transaction_id:'T001'}) SET t.amount=450000.00, t.transaction_date=datetime('2026-08-10 14:30:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P001'}), (t:Transaction {transaction_id:'T001'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T001'}), (r:Person {person_id:'P002'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T002'}) SET t.amount=120000.00, t.transaction_date=datetime('2026-08-11 11:20:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P003'}), (t:Transaction {transaction_id:'T002'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T002'}), (r:Person {person_id:'P001'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T003'}) SET t.amount=80000.00, t.transaction_date=datetime('2026-08-12 09:15:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P002'}), (t:Transaction {transaction_id:'T003'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T003'}), (r:Person {person_id:'P004'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T004'}) SET t.amount=175000.00, t.transaction_date=datetime('2026-08-18 10:30:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P006'}), (t:Transaction {transaction_id:'T004'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T004'}), (r:Person {person_id:'P007'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T005'}) SET t.amount=95000.00, t.transaction_date=datetime('2026-08-19 12:15:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P007'}), (t:Transaction {transaction_id:'T005'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T005'}), (r:Person {person_id:'P008'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T006'}) SET t.amount=210000.00, t.transaction_date=datetime('2026-08-21 15:45:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P008'}), (t:Transaction {transaction_id:'T006'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T006'}), (r:Person {person_id:'P009'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T007'}) SET t.amount=65000.00, t.transaction_date=datetime('2026-08-23 09:20:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P009'}), (t:Transaction {transaction_id:'T007'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T007'}), (r:Person {person_id:'P010'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T008'}) SET t.amount=320000.00, t.transaction_date=datetime('2026-08-24 18:10:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P010'}), (t:Transaction {transaction_id:'T008'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T008'}), (r:Person {person_id:'P006'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T009'}) SET t.amount=110000.00, t.transaction_date=datetime('2026-08-26 11:05:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P011'}), (t:Transaction {transaction_id:'T009'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T009'}), (r:Person {person_id:'P012'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T010'}) SET t.amount=275000.00, t.transaction_date=datetime('2026-08-27 14:40:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P012'}), (t:Transaction {transaction_id:'T010'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T010'}), (r:Person {person_id:'P013'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T011'}) SET t.amount=85000.00, t.transaction_date=datetime('2026-08-29 16:30:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P013'}), (t:Transaction {transaction_id:'T011'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T011'}), (r:Person {person_id:'P014'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T012'}) SET t.amount=190000.00, t.transaction_date=datetime('2026-08-30 13:25:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P014'}), (t:Transaction {transaction_id:'T012'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T012'}), (r:Person {person_id:'P015'}) MERGE (t)-[:TRANSFERRED_TO]->(r);
MERGE (t:Transaction {transaction_id:'T013'}) SET t.amount=125000.00, t.transaction_date=datetime('2026-08-31 17:50:00'), t.transaction_type='Digital';
MATCH (s:Person {person_id:'P015'}), (t:Transaction {transaction_id:'T013'}) MERGE (s)-[:MADE]->(t);
MATCH (t:Transaction {transaction_id:'T013'}), (r:Person {person_id:'P006'}) MERGE (t)-[:TRANSFERRED_TO]->(r);

MERGE (e:Evidence {evidence_id:'E001'}) SET e.evidence_type='CCTV', e.description='Vehicle observed near location', e.status='Verified';
MATCH (e:Evidence {evidence_id:'E001'}), (c:Case {case_id:'C1042'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E002'}) SET e.evidence_type='Witness', e.description='Witness reported meeting between two persons', e.status='Reported';
MATCH (e:Evidence {evidence_id:'E002'}), (c:Case {case_id:'C1042'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E003'}) SET e.evidence_type='Financial', e.description='Transaction associated with person network', e.status='Verified';
MATCH (e:Evidence {evidence_id:'E003'}), (c:Case {case_id:'C1042'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E004'}) SET e.evidence_type='Cash Event', e.description='Reported cash exchange with no digital record', e.status='Unverified';
MATCH (e:Evidence {evidence_id:'E004'}), (c:Case {case_id:'C1042'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E005'}) SET e.evidence_type='CCTV', e.description='Vehicle observed near incident location', e.status='Verified';
MATCH (e:Evidence {evidence_id:'E005'}), (c:Case {case_id:'C1205'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E006'}) SET e.evidence_type='Witness', e.description='Witness reported suspicious meeting', e.status='Reported';
MATCH (e:Evidence {evidence_id:'E006'}), (c:Case {case_id:'C1210'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E007'}) SET e.evidence_type='Financial', e.description='Transaction linked to investigation network', e.status='Verified';
MATCH (e:Evidence {evidence_id:'E007'}), (c:Case {case_id:'C1215'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E008'}) SET e.evidence_type='CCTV', e.description='Vehicle appeared near location', e.status='Verified';
MATCH (e:Evidence {evidence_id:'E008'}), (c:Case {case_id:'C1220'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E009'}) SET e.evidence_type='Witness', e.description='Person reported suspicious activity', e.status='Reported';
MATCH (e:Evidence {evidence_id:'E009'}), (c:Case {case_id:'C1225'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E010'}) SET e.evidence_type='Financial', e.description='Unusual transaction identified', e.status='Verified';
MATCH (e:Evidence {evidence_id:'E010'}), (c:Case {case_id:'C1230'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E011'}) SET e.evidence_type='Phone', e.description='Phone activity associated with investigation', e.status='Verified';
MATCH (e:Evidence {evidence_id:'E011'}), (c:Case {case_id:'C1205'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E012'}) SET e.evidence_type='Vehicle', e.description='Vehicle associated with person of interest', e.status='Reported';
MATCH (e:Evidence {evidence_id:'E012'}), (c:Case {case_id:'C1210'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E013'}) SET e.evidence_type='Document', e.description='Financial document submitted for review', e.status='Verified';
MATCH (e:Evidence {evidence_id:'E013'}), (c:Case {case_id:'C1215'}) MERGE (e)-[:SUPPORTS]->(c);
MERGE (e:Evidence {evidence_id:'E014'}) SET e.evidence_type='Digital', e.description='Digital record requires further verification', e.status='Unverified';
MATCH (e:Evidence {evidence_id:'E014'}), (c:Case {case_id:'C1230'}) MERGE (e)-[:SUPPORTS]->(c);

MATCH (c:Case {case_id:'C1042'}), (l:Location {location_id:'L001'}) MERGE (c)-[:OCCURRED_AT]->(l);
MATCH (c:Case {case_id:'C0817'}), (l:Location {location_id:'L002'}) MERGE (c)-[:OCCURRED_AT]->(l);
MATCH (c:Case {case_id:'C0562'}), (l:Location {location_id:'L003'}) MERGE (c)-[:OCCURRED_AT]->(l);
MATCH (c:Case {case_id:'C0301'}), (l:Location {location_id:'L001'}) MERGE (c)-[:OCCURRED_AT]->(l);
MATCH (c:Case {case_id:'C1205'}), (l:Location {location_id:'L005'}) MERGE (c)-[:OCCURRED_AT]->(l);
MATCH (c:Case {case_id:'C1210'}), (l:Location {location_id:'L006'}) MERGE (c)-[:OCCURRED_AT]->(l);
MATCH (c:Case {case_id:'C1215'}), (l:Location {location_id:'L007'}) MERGE (c)-[:OCCURRED_AT]->(l);
MATCH (c:Case {case_id:'C1220'}), (l:Location {location_id:'L005'}) MERGE (c)-[:OCCURRED_AT]->(l);
MATCH (c:Case {case_id:'C1225'}), (l:Location {location_id:'L008'}) MERGE (c)-[:OCCURRED_AT]->(l);
MATCH (c:Case {case_id:'C1230'}), (l:Location {location_id:'L006'}) MERGE (c)-[:OCCURRED_AT]->(l);

MATCH (n) RETURN labels(n) AS label, count(n) AS count ORDER BY label;
MATCH ()-[r]->() RETURN type(r) AS relationship, count(r) AS count ORDER BY relationship;
MATCH (p:Person)-[:USES]->(ph:Phone) RETURN p.person_id, p.name, ph.phone_id, ph.phone_number ORDER BY p.person_id;
MATCH (p:Person)-[:OWNS]->(v:Vehicle) RETURN p.person_id, p.name, v.vehicle_id, v.registration_no ORDER BY p.person_id;
MATCH (p:Person)-[:OWNS]->(a:Account) RETURN p.person_id, p.name, a.account_id, a.account_type ORDER BY p.person_id;
MATCH (c:Case)-[:OCCURRED_AT]->(l:Location) RETURN c.case_id, c.crime_type, c.case_date, c.status, l.location_name, l.city ORDER BY c.case_id;
MATCH (s:Person)-[:MADE]->(t:Transaction)-[:TRANSFERRED_TO]->(r:Person) RETURN t.transaction_id, s.person_id AS sender, r.person_id AS receiver, t.amount, t.transaction_date ORDER BY t.transaction_id;
MATCH (e:Evidence)-[:SUPPORTS]->(c:Case) RETURN e.evidence_id, e.evidence_type, e.status, c.case_id ORDER BY e.evidence_id;

MATCH (p:Person)-[:MADE]->(t:Transaction)-[:TRANSFERRED_TO]->(r:Person) WHERE t.amount >= 200000 RETURN p.name AS sender, r.name AS receiver, t.amount, t.transaction_date ORDER BY t.amount DESC;
MATCH (c:Case)-[:OCCURRED_AT]->(l:Location)<-[:OCCURRED_AT]-(other:Case) WHERE c.case_id < other.case_id RETURN c.case_id, other.case_id, l.location_name;
MATCH (p:Person)-[:MADE]->(t:Transaction)-[:TRANSFERRED_TO]->(r:Person) RETURN p.person_id, p.name, count(t) AS sent_transactions ORDER BY sent_transactions DESC;
MATCH (e:Evidence)-[:SUPPORTS]->(c:Case) RETURN c.case_id, c.crime_type, count(e) AS evidence_count ORDER BY evidence_count DESC;
